### ISSUE TITLE
Installation auf Contao 4.9.3

### ISSUE THREAD

**Issue by bixicy** [heimrichhannot/contao-quiz-bundle#1]
Hallo,

wie lässt sich die Erweiterung aktuell auf Version 4.9.3 installieren?

über composer geht das leider nicht mit der beta4 
`composer require heimrichhannot/contao-quiz-bundle ~1.0.0-beta4`

```
mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 1409294336) (tried to allocate 134217736 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSet.php on line 84
```

**Comment by koertho** [comment]
@bixicy Hi, das ist kein Bundle-spezifischer Fehler, sondern dein PHP-Prozess hat zu wenig speicher. Du könntest diesen in der php.ini oder über einen Parameter hochsetzen, um den Fehler zu umgehen.
