### ISSUE TITLE
French translation is not displayed

### ISSUE THREAD

**Issue by tjaulin** [heimrichhannot/contao-quiz-bundle#3]
Hello,

I have a project to set up a quiz, but the French translation does not display. I thought since this is a beta it may not be implemented?

 I am under Contao version 4.4.45, I tried to add in "vendor \ heimrichhannot \ contao-quiz-bundle \ src \ Resources \ translations" a .yml file named "messages.fr.yml" for the translation in French and it doesn't work, and I also tried adding a file "messages.en.yml" in the same folder for the English translation, but it doesn't work either and only the German language works.

 So my question is, do you know how to integrate the French language into your module?

**Comment by koertho** [comment]
@tjaulin Simple question: have you cleared your cache?

**Comment by tjaulin** [comment]
Yes, I just tried again and it still doesn't work

**Comment by tjaulin** [comment]
Update : 
Its works!
I cleared all the caches with the contao manager after replacing the German by French. Thank you for your help, have a good day !

**Comment by koertho** [comment]
@tjaulin Thanks for reporting back. I just testet it by myself and it also worked, it was just a cache problem in your case. 

I also fixed some bugs in the latest release. To be honest, the bundle is not really good maintained as it's not currently used, old and the original maintainer is not in our company anymore. But if it's good for your, have fun :)
