### ISSUE TITLE
Weiterentwicklung geplant?

### ISSUE THREAD

**Issue by skipman** [heimrichhannot/contao-quiz-bundle#5]
Kurze Frage:
Nachdem die Erweiterung noch im Beta-Stadium ist, wollt ich mal kurz nachfragen, ob noch weiterentwickelt wird. Ich verwende aktuell Contao 4.9 mit PHP 8.1 weshalb sich die Erweiterung nicht installieren lässt. Der 2. Grund ist das 'dev' - Stadium, aber das lässt sich sicher umgehen. Nur die PHP-Version möchte ich nicht heruntersetzen.

**Comment by koertho** [comment]
Bei so speziellen Erweiterungen ist es meist so, dass wir nur daran arbeiten, wenn es ein Projekt verlangt. Daher kann ich leider nicht sagen, wann und ob wir an der Erweiterung  wieder arbeiten werden. PHP 8 kann ich dir gerne ungetestet freigeben. Ansonsten darfst du gerne Pull-Requests einreichen.

**Comment by koertho** [comment]
PHP 8 ist freigegeben

**Comment by skipman** [comment]
Vielen Dank für den raschen response! Werde das mal demnächst testen!
