### ISSUE TITLE
Installationsfehler

### ISSUE THREAD

**Issue by Zkippy** [heimrichhannot/contao-quiz-bundle#6]
Hallo,
erstmal möchte ich einmal Danke sagen für die Erweiterung, auch wenn ich sie aktuell nicht nutzen kann.
Bin nur ein besserer Anwender, daher kann ich gar nicht soviel sagen. Habe versucht die Erweiterung über den Manager zu laden, erhalte aber eine Fehlermeldung (siehe unten). Habe einen Freund gebeten, diese zu installieren, was auch funktionert hat bei ähnlicher Konfig. Allerdings wird auch hier ein Fehler geschmissen im FE.
Ich weiß es handelt sich aktuell noch um eine Beta-Version, daher keinen Stress, würde mich sehr über eine Release-Version freuen ;-)

**Context**
Contao version: 4.12
Bundle version:  8Beta
PHP version: 7.4

**Description**
In InitCommand.php line 950:
                                                                               
  Could not find a version of package heimrichhannot/contao-quiz-bundle match  
  ing your minimum-stability (stable). Require it with an explicit version co  
  nstraint allowing its desired stability.                                     
                                                                               
require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
# Process terminated with exit code 1
# Result: General error

Viele Grüße

**Comment by koertho** [comment]
Hi, das ist kein direkter Bundle-Fehler, sondern eine fehlende Konfiguration in deiner composer.json: https://getcomposer.org/doc/04-schema.md#minimum-stability

Abseits davon möchte ich zum Thema Weiterentwicklung auf https://github.com/heimrichhannot/contao-quiz-bundle/issues/5 verweisen.
